language:
  - ruby
rvm:
  - 2.3.0
sudo: false
services:
  - postgresql
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - sqlite3
  postgres: 9.3
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
install:
  - bundle install
  - nvm install 5.5
  - nvm use 5.5
  - npm install
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - psql -c 'create database lingista_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - DRIVER=selenium_firefox bundle exec rake
  - bundle exec rake lint
