default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: lingita_development

test:
  <<: *default
  database: lingita_test
  password: ~
